name: quickwiz_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  http: ^1.1.0
  http_interceptor: ^2.0.0-beta.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SpaceGrotesk
      fonts:
      - asset: assets/fonts/SpaceGroteskBold.ttf
      - asset: assets/fonts/SpaceGroteskLight.ttf
      - asset: assets/fonts/SpaceGroteskMedium.ttf
      - asset: assets/fonts/SpaceGroteskRegular.ttf
      - asset: assets/fonts/SpaceGroteskSemiBold.ttf
    - family: Urbanist
      fonts:
      - asset: assets/fonts/UrbanistBold.ttf
      - asset: assets/fonts/UrbanistLight.ttf
      - asset: assets/fonts/UrbanistRegular.ttf
