name: quickwiz_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  http: ^1.1.0
  http_interceptor: ^2.0.0-beta.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
      - asset: assets/fonts/PoppinsRegular.ttf
      - asset: assets/fonts/PoppinsBold.ttf
      - asset: assets/fonts/PoppinsBoldItalic.ttf
      - asset: assets/fonts/PoppinsItalic.ttf
      - asset: assets/fonts/PoppinsMedium.ttf
      - asset: assets/fonts/PoppinsSemiBold.ttf
    - family: Roboto
      fonts:
      - asset: assets/fonts/RobotoRegular.ttf
      - asset: assets/fonts/RobotoBold.ttf
